import { Box, Center, Spinner } from "@chakra-ui/react";
import React, { useEffect, useState } from "react";
import Nav from "../Nav";
import Head from "next/head";

interface LayoutProps {
  title: string;
  children: JSX.Element;
}

export default function Layout({ children, title }: LayoutProps) {
  const [loading, setLoading] = useState(false);

  return (
    <Box w="100%" bgColor="plain" m="0px" p="0px" minH="100vh" overflow="auto" h="100%">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Nav loading={loading} setLoading={setLoading} />
      {loading && (
        <Center w="100%" pt="300px">
          <Spinner color="primary" size="xl" thickness="10px" speed="0.65s" emptyColor="secondary" />
        </Center>
      )}
      {!loading && <Box>{children}</Box>}
    </Box>
  );
}
